### ISSUE TITLE
Test todo

### ISSUE THREAD

**Issue by PathogenDavid** [PathogenDavid/EnumerateTraversalProjects#1]
- [ ] NestedTraversal2
- [ ] Shared Items Projects (shproj)
- [ ] Analyzer project imports
- [ ] F# (fsproj)
- [ ] VisualBasic (vbproj)
- [ ] C++/CLI
- [ ] Look at the [Xamarin.MSBuild.Sdk tests](https://github.com/xamarin/mirepoix/tree/master/src/Xamarin.MSBuild.Sdk.Tests/Solutions)
- [ ] SDK variants (Maybe not strictly necessary to test all of these.)
  - [ ] Winforms/WPF projects
  - [ ] ASP.NET projects
  - [ ] Blazor projects
- [ ] Look for any weird project types supported by dotnet CLI

# Less common project types

- [ ] Python (pyproj)
- [ ] JavaScript/TypeScript (njsproj)
- [ ] Windows App Package Project (wapproj)
- [ ] SQL Server Database Project (sqlproj) (No idea how even to test this one.)

Note: See Lovelace/NodejsConsoleApp1 for a bunch of the weirder projects.

**Comment by PathogenDavid** [comment]
Test a project graph like this:

```dot
dirs.proj -> Application.csproj
dirs.proj -> ClassLibrary2.csproj
Application.csproj -> ClassLibrary.csproj
ClassLibrary.csproj -> ClassLibrary2.csproj
```

Should be fine, want to make sure `ClassLibrary2` doesn't get duped.

**Comment by PathogenDavid** [comment]
A good torture test might be to make a Traversal project that only directly references the `csc` project of Roslyn.
